# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_ARCHIVE_GID "-1")
set(CPACK_ARCHIVE_UID "-1")
set(CPACK_BUILD_SOURCE_DIRS "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd;/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/models/share/userdata/cb/AscendFast/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "opp built using CMake")
set(CPACK_EXTERNAL_BUILT_PACKAGES "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out/_CPack_Packages/Linux/External/custom_opp_openEuler_aarch64.run/custom_opp_openEuler_aarch64.run")
set(CPACK_EXTERNAL_ENABLE_STAGING "TRUE")
set(CPACK_EXTERNAL_PACKAGE_SCRIPT "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/cmake/makeself.cmake")
set(CPACK_GENERATOR "External")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out;opp;ALL;/")
set(CPACK_INSTALL_PREFIX "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out")
set(CPACK_MODULE_PATH "")
set(CPACK_NSIS_DISPLAY_NAME "opp 0.1.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "opp 0.1.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out/CPackConfig.cmake")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION "CPack opp project")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/models/share/userdata/cb/AscendFast/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "CPack opp project")
set(CPACK_PACKAGE_DIRECTORY "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out")
set(CPACK_PACKAGE_FILE_NAME "custom_opp_openEuler_aarch64.run")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "opp 0.1.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "opp 0.1.1")
set(CPACK_PACKAGE_NAME "opp")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Humanity")
set(CPACK_PACKAGE_VERSION "0.1.1")
set(CPACK_PACKAGE_VERSION_MAJOR "0")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/models/share/userdata/cb/AscendFast/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "/models/share/userdata/cb/AscendFast/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/models/share/userdata/cb/AscendFast/.venv/lib/python3.10/site-packages/cmake/data/share/cmake-4.3/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out/CPackSourceConfig.cmake")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/models/share/userdata/cb/AscendFast/kernels/ascendc_ops/add_demo/AddDemoStd/build_out/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
